# This file is automatically generated. Do not edit.

if Object.const_defined?('TestFlight') and !UIDevice.currentDevice.model.include?('Simulator')
  NSNotificationCenter.defaultCenter.addObserverForName(UIApplicationDidBecomeActiveNotification, object:nil, queue:nil, usingBlock:lambda do |notification|
  TestFlight.setDeviceIdentifier(UIDevice.currentDevice.uniqueIdentifier)
  TestFlight.takeOff('b4ab9455-0e67-44f7-8fc7-9d9c34176c86')
  end)
end
